package pl2.darioedu;
public class PanelLogin extends javax.swing.JFrame {    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelLogin.class.getName());
    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
        this.setTitle("JavaFit - Login Menu - "+Globales.version);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonAcceder = new javax.swing.JButton();
        jButtonAyuda = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Caladea", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JavaFit");
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 60));

        jPasswordField1.setBackground(new java.awt.Color(255, 204, 102));
        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);

        jButtonAcceder.setBackground(new java.awt.Color(255, 153, 0));
        jButtonAcceder.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonAcceder.setText("Acceder");
        jButtonAcceder.setMaximumSize(new java.awt.Dimension(70, 20));
        jButtonAcceder.setMinimumSize(new java.awt.Dimension(70, 20));
        jButtonAcceder.setPreferredSize(new java.awt.Dimension(70, 20));
        jButtonAcceder.addActionListener(this::jButtonAccederActionPerformed);

        jButtonAyuda.setBackground(new java.awt.Color(255, 153, 0));
        jButtonAyuda.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonAyuda.setText("Ayuda");
        jButtonAyuda.addActionListener(this::jButtonAyudaActionPerformed);

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 204, 102));
        jTextFieldUsuario.addActionListener(this::jTextFieldUsuarioActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("La contraseña / usuario introducido es incorrecta.");
        jLabel2.setEnabled(false);

        jButton3.setText("jButton3");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButton2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
       this.jLabel2.setVisible(false);
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed

    }//GEN-LAST:event_jButtonAccederActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        this.jLabel2.setVisible(false);
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    public final String getUsuario(){
        return this.jTextFieldUsuario.getText();
    }
    public final String getHash(){
        String contra = String.valueOf(this.jPasswordField1.getPassword());
        String hash = GestorSeguridad.hashearContra(contra);
        return hash;
    }
    public void autenticar(){
        // POR HACER
    }
    public void crearPanel(Usuario usuarioEncontrado){
        if (usuarioEncontrado instanceof Administrador) {
    
    
    Administrador elAdmin = (Administrador) usuarioEncontrado;
    
    
    PanelAdmin panelAdmin = new PanelAdmin(elAdmin);
    panelAdmin.setVisible(true);
    
} else if (usuarioEncontrado instanceof Socio) {
    
    // IMPORTANTE, ESTA PUESTO LAS BARRAS PARA QUE COMPILE, HAY QUE QUITARLAS CUANDO ESO
    Socio elSocio = (Socio) usuarioEncontrado;
    // PanelSocio panelSocio = new PanelSocio(elSocio);
    this.setVisible(false);
    //panelSocio.setVisible(true);
    this.dispose();
    
}
    }
    public void cerrarVentana(){
        //Cerrar ventana en forma de código: https://stackoverflow.com/questions/1234912/how-to-programmatically-close-a-jframe
            this.setVisible(false);
            this.dispose();
    }
    public void imprimirInvalido(){
        this.jLabel2.setVisible(true);
    }
    public void imprimirEspecifico(String mensaje){
        //Si quieremos devolver un mensaje de invalidez espcífico; longitud máxima de 50 caracteres, incluidos espacios)
        this.jLabel2.setText(mensaje);
        this.jLabel2.setVisible(true);
    }
    public boolean validarCampos(){
        return(false); }
}
