/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl2.darioedu;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * Ventana modificar datos personales
 * @author Eduardo
 * Esta es la ventana que permite modificar los datos personales del socio que lo haya solicitado
 */
public class PanelModificarDatosPersonales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelModificarDatosPersonales.class.getName());
    private Socio socio;
    private String direccion;
    private ArrayList<String> tarjeta;
    private String telefono;
    private boolean isVip;
    protected String nombre;
    protected String correo;
    protected String correoIni;
    protected String sal;
    protected String hasheo;
    
    private String nuevaContra;
    /**
     * Creates new form PanelModificarDatosPersonales
     * @param soci
     */
    public PanelModificarDatosPersonales(Socio soci) {
        initComponents();
        this.socio = soci;
        this.direccion = soci.getDireccion();
        this.tarjeta = soci.getTarjeta();
        this.correoIni = soci.getCorreo();
        this.nombre = soci.getNombre();
        this.telefono = soci.getTelefono();
        this.sal = soci.getSal();
        this.hasheo = soci.getHash();
        this.isVip = soci.getVipStatus();
        this.jLabelErrorContra.setVisible(false);
        // SOLO HE HECHO ESTE CONSTRUCTOR, QUEDA EL RESTO DE FUNCIONES DE LOS BOTONES
        this.jTextFieldNombre.setText(this.nombre);
        this.jTextFieldCorreo.setText(this.correoIni);
        this.jTextFieldDireccion.setText(this.direccion);
        this.jFormattedTextFieldTLF.setValue(GestorSeguridad.codificar(this.telefono, 5));
        this.jFormattedTextFieldNumTarjeta.setValue(GestorSeguridad.codificar(this.tarjeta.get(0), 5));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldTLF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldNumTarjeta = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCad = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldCVV = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonSI = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonVolverAtras = new javax.swing.JButton();
        jButtonCambiarDatos = new javax.swing.JButton();
        jLabelErrorContra = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BotonAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit - User Data Modify - Version "+Globales.version);

        jTextFieldDireccion.addActionListener(this::jTextFieldDireccionActionPerformed);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Correo");

        jLabel3.setText("Direccion");

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        jLabel4.setText("Nueva Contraseña (Opcional, dejar vacío si no se quiere cambiar)");

        jLabel5.setText("Confirmar Nueva Contraseña");

        try {
            jFormattedTextFieldTLF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Telefono");

        try {
            jFormattedTextFieldNumTarjeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCad.setMinimumSize(new java.awt.Dimension(64, 47));
        jFormattedTextFieldCad.setPreferredSize(new java.awt.Dimension(64, 47));

        jLabel7.setText("Numero de Tarjeta");

        jLabel8.setText("Caducidad");

        try {
            jFormattedTextFieldCVV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("CVV");

        jLabel10.setText("¿Ser Socio VIP?");

        jButtonSI.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSI.setText("Si");
        jButtonSI.addActionListener(this::jButtonSIActionPerformed);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("No");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel11.setText(" (Dejar en blanco si no se desea cambiar)");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setText("<html><center>Nota: Cambiar el<br>estado puede<br>provocar un<br>cargo en<br>la tarjeta<center></html>");

        jButtonVolverAtras.setBackground(new java.awt.Color(255, 153, 51));
        jButtonVolverAtras.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonVolverAtras.setText("<html><center>Volver<br>Atras<center></html>");
        jButtonVolverAtras.addActionListener(this::jButtonVolverAtrasActionPerformed);

        jButtonCambiarDatos.setBackground(new java.awt.Color(255, 153, 51));
        jButtonCambiarDatos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonCambiarDatos.setText("Cambiar Datos");
        jButtonCambiarDatos.addActionListener(this::jButtonCambiarDatosActionPerformed);

        jLabelErrorContra.setForeground(new java.awt.Color(255, 51, 51));
        jLabelErrorContra.setText("Las contraseñas deben coincidir");

        jLabel13.setText("Nota: Al cambiar los datos, se cerrará la sesión actual");

        BotonAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AyudaBoton.png"))); // NOI18N
        BotonAyuda.setMaximumSize(new java.awt.Dimension(50, 50));
        BotonAyuda.setMinimumSize(new java.awt.Dimension(50, 50));
        BotonAyuda.setPreferredSize(new java.awt.Dimension(50, 50));
        BotonAyuda.addActionListener(this::BotonAyudaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldDireccion)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField2))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorContra))
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldNumTarjeta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonCambiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(BotonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jFormattedTextFieldCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jFormattedTextFieldCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(25, 25, 25)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jButtonSI, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel10)))
                                                .addComponent(jLabel13))
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(jFormattedTextFieldTLF))))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelErrorContra))
                .addGap(5, 5, 5)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldTLF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFormattedTextFieldCVV)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonSI, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonCambiarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(BotonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jButtonCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarDatosActionPerformed
    ArrayList<Usuario> listaUser = UtilTienda.getInstancia().getListaUsuarioStatic();
    Socio usuarioEncontrado = (Socio) listaUser.stream().filter(u -> u.getCorreo().equals(this.correoIni)).findFirst().orElse(null);
    
    if (Arrays.equals(this.jPasswordField1.getPassword(), jPasswordField2.getPassword())){        
        if (!(this.jTextFieldNombre.getText().equals(""))){
                this.nombre = this.jTextFieldNombre.getText();
                usuarioEncontrado.setNombre(this.nombre);
            }
            if (!(this.jTextFieldCorreo.getText().equals(""))){
                this.correo = this.jTextFieldCorreo.getText();
                usuarioEncontrado.cambiarCorreo(this.correo);
            }
            if (!(this.jTextFieldDireccion.getText().equals(""))){
                this.direccion = this.jTextFieldDireccion.getText();
                usuarioEncontrado.cambiarDireccion(this.direccion);
            }
            if (!(this.jFormattedTextFieldTLF.getText().equals(""))){
                this.telefono = this.jFormattedTextFieldTLF.getText();
                usuarioEncontrado.cambiarTelefono(this.telefono);
            }
            if (!(this.jPasswordField1.getPassword() == null)){
                this.nuevaContra = String.valueOf(this.jPasswordField1.getPassword());
                usuarioEncontrado.cambiarContra(this.nuevaContra);
            }
            if (!(this.jFormattedTextFieldNumTarjeta.getText().equals(""))){
                this.tarjeta.clear();
                this.tarjeta.add(jFormattedTextFieldNumTarjeta.getText());
                this.tarjeta.add(jFormattedTextFieldCad.getText());
                usuarioEncontrado.cambiarTarjeta(this.tarjeta);
            }
            usuarioEncontrado.cambiarStatusVip(this.isVip);
            UtilTienda.getInstancia().guardarListaUsuarios(listaUser);
            
            PanelLogin ventanaLogueo = new PanelLogin();
            this.setVisible(false);
            ventanaLogueo.setVisible(true);
            this.dispose();
            
        }
    else{
        this.jLabelErrorContra.setVisible(true);
    }
    }//GEN-LAST:event_jButtonCambiarDatosActionPerformed

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed
        PanelUsuario ventanaUSU = new PanelUsuario(socio);
        this.setVisible(false);
        ventanaUSU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIActionPerformed
        this.isVip = true;
        this.jButtonSI.setBackground(Color.GREEN);
        this.jButton1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonSIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.isVip = false;
        this.jButtonSI.setBackground(Color.LIGHT_GRAY);
        this.jButton1.setBackground(Color.RED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAyudaActionPerformed
        new PanelAyuda("Este panel sirve para que puedas cambiar la información acerca del usuario").setVisible(true);
    }//GEN-LAST:event_BotonAyudaActionPerformed
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAyuda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCambiarDatos;
    private javax.swing.JButton jButtonSI;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JFormattedTextField jFormattedTextFieldCVV;
    private javax.swing.JFormattedTextField jFormattedTextFieldCad;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumTarjeta;
    private javax.swing.JFormattedTextField jFormattedTextFieldTLF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorContra;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
