/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl2.darioedu;

/**
 *
 * @author User
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelAdmin.class.getName());
    private final Administrador usuario;
    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin(Administrador admin) {
        initComponents();
        this.usuario = admin ;
        NombreUsuario.setText(usuario.getNombre()) ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JTextField();
        jButtonGestAct = new javax.swing.JButton();
        jButtonConsAct = new javax.swing.JButton();
        jButtonReservas = new javax.swing.JButton();
        jButtonSocios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        NombreUsuario.setEditable(false);
        NombreUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        NombreUsuario.setText("jTextField1");

        jButtonGestAct.setBackground(new java.awt.Color(255, 153, 0));
        jButtonGestAct.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonGestAct.setText("<html><center>Gestionar<br>Actividades<center></html>");
        jButtonGestAct.addActionListener(this::jButtonGestActActionPerformed);

        jButtonConsAct.setBackground(new java.awt.Color(255, 153, 0));
        jButtonConsAct.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonConsAct.setText("<html><center>Consultar<br>Actividades<center></html>");

        jButtonReservas.setBackground(new java.awt.Color(255, 153, 0));
        jButtonReservas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonReservas.setText("<html><center>Consultar<br>Reservas<center></html>");

        jButtonSocios.setBackground(new java.awt.Color(255, 153, 0));
        jButtonSocios.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonSocios.setText("<html><center>Consultar<br>Socios<center></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGestAct, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSocios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConsAct, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGestAct, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jButtonConsAct))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonReservas)
                    .addComponent(jButtonSocios, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestActActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
    // 1. Creamos un administrador falso solo para esta prueba de diseño
    Administrador adminDummy = new Administrador("Jefe Prueba", "admin@javafit.com", "0000");
    
    // 2. Se lo pasamos a la ventana para que nos permita construirla
    new PanelAdmin(adminDummy).setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JButton jButtonConsAct;
    private javax.swing.JButton jButtonGestAct;
    private javax.swing.JButton jButtonReservas;
    private javax.swing.JButton jButtonSocios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}

