/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl2.darioedu;

/**
 *
 * @author User
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelAdmin.class.getName());
    private final Administrador usuario;
    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin(Administrador admin) {
        initComponents();
        this.usuario = admin ;
        NombreUsuario.setText(usuario.getNombre()) ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JTextField();
        jButtonGestAct = new javax.swing.JButton();
        jButtonConsAct = new javax.swing.JButton();
        jButtonReservas = new javax.swing.JButton();
        jButtonSocios = new javax.swing.JButton();
        jButtonCrearAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 315));
        setMinimumSize(new java.awt.Dimension(400, 315));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        NombreUsuario.setEditable(false);
        NombreUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        NombreUsuario.setText("jTextField1");

        jButtonGestAct.setBackground(new java.awt.Color(255, 153, 0));
        jButtonGestAct.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonGestAct.setText("<html><center>Gestionar<br>Actividades<center></html>");
        jButtonGestAct.setMinimumSize(new java.awt.Dimension(132, 80));
        jButtonGestAct.setPreferredSize(new java.awt.Dimension(132, 80));
        jButtonGestAct.addActionListener(this::jButtonGestActActionPerformed);

        jButtonConsAct.setBackground(new java.awt.Color(255, 153, 0));
        jButtonConsAct.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonConsAct.setText("<html><center>Consultar<br>Actividades<center></html>");
        jButtonConsAct.setMinimumSize(new java.awt.Dimension(132, 80));
        jButtonConsAct.setPreferredSize(new java.awt.Dimension(132, 80));
        jButtonConsAct.addActionListener(this::jButtonConsActActionPerformed);

        jButtonReservas.setBackground(new java.awt.Color(255, 153, 0));
        jButtonReservas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonReservas.setText("<html><center>Consultar<br>Reservas<center></html>");
        jButtonReservas.setMinimumSize(new java.awt.Dimension(132, 80));
        jButtonReservas.setPreferredSize(new java.awt.Dimension(132, 80));
        jButtonReservas.addActionListener(this::jButtonReservasActionPerformed);

        jButtonSocios.setBackground(new java.awt.Color(255, 153, 0));
        jButtonSocios.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonSocios.setText("<html><center>Consultar<br>Socios<center></html>");
        jButtonSocios.setMinimumSize(new java.awt.Dimension(132, 80));
        jButtonSocios.setPreferredSize(new java.awt.Dimension(132, 80));
        jButtonSocios.addActionListener(this::jButtonSociosActionPerformed);

        jButtonCrearAdmin.setBackground(new java.awt.Color(255, 204, 51));
        jButtonCrearAdmin.setText("Crear Admin");
        jButtonCrearAdmin.addActionListener(this::jButtonCrearAdminActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCrearAdmin)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGestAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsAct, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCrearAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGestAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestActActionPerformed
        PanelGestionActividades panel1 = new PanelGestionActividades(this.usuario);
        this.setVisible(false);
        panel1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGestActActionPerformed

    private void jButtonCrearAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearAdminActionPerformed
        PanelNuevoAdmin panel = new PanelNuevoAdmin(this.usuario);
        this.setVisible(false);
        panel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCrearAdminActionPerformed

    private void jButtonConsActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsActActionPerformed
        PanelConsultaActividades panel2 = new PanelConsultaActividades(this.usuario);
        this.setVisible(false);
        panel2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonConsActActionPerformed

    private void jButtonSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSociosActionPerformed
        PanelConsultaSocios panel3 = new PanelConsultaSocios(this.usuario);
        this.setVisible(false);
        panel3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSociosActionPerformed

    private void jButtonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservasActionPerformed
        PanelConsultaReservas panel4 = new PanelConsultaReservas(this.usuario);
        this.setVisible(false);
        panel4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JButton jButtonConsAct;
    private javax.swing.JButton jButtonCrearAdmin;
    private javax.swing.JButton jButtonGestAct;
    private javax.swing.JButton jButtonReservas;
    private javax.swing.JButton jButtonSocios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}

