/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl2.darioedu;

import java.util.ArrayList;

/**
 *
 * @author User
 */
public class PanelUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelUsuario.class.getName());
    private static Socio socio;
    /**
     * Creates new form PanelUsuario
     */
    public PanelUsuario(Socio soci) {
        initComponents();
        this.socio = soci;
        this.jLabelNomUsuario.setText(this.socio.getNombre());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNomUsuario = new javax.swing.JLabel();
        jButtonActividades = new javax.swing.JButton();
        jButtonReservas = new javax.swing.JButton();
        jButtonDatosPersonales = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido,");

        jLabelNomUsuario.setText("jLabel2");

        jButtonActividades.setBackground(new java.awt.Color(255, 153, 51));
        jButtonActividades.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonActividades.setText("<html><center>Calendario<br>de<br>Actividades<center></html>");
        jButtonActividades.addActionListener(this::jButtonActividadesActionPerformed);

        jButtonReservas.setBackground(new java.awt.Color(255, 153, 51));
        jButtonReservas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonReservas.setText("<html><center>Gestionar<br>Reservas<center></html>");
        jButtonReservas.addActionListener(this::jButtonReservasActionPerformed);

        jButtonDatosPersonales.setBackground(new java.awt.Color(255, 153, 51));
        jButtonDatosPersonales.setText("<html><center>Modificar<br>Datos personales<center></html>");
        jButtonDatosPersonales.addActionListener(this::jButtonDatosPersonalesActionPerformed);

        jLabel2.setText("<html><div style='text-align: center; font-family: sans-serif; color: #333333;'>\n        Consulta las <b>próximas actividades</b> del gimnasio,<br>\n        y <font color='#2E86C1'><b>reserva tu plaza</b></font> para tu siguiente aventura 🚀\n        </div></html>");

        jLabel3.setText("<html><div style='text-align: center; font-family: sans-serif; color: #333333;'>\n        <b>Consulta</b>, <b>modifica</b> o <font color='#CB4335'><b>elimina</b></font><br>\n        tus reservas de actividades futuras 📅\n        </div></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jButtonDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelNomUsuario))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButtonActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jButtonReservas))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActividadesActionPerformed
        PanelUsuActividades panel = new PanelUsuActividades(this.socio);
        this.setVisible(false);
        panel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonActividadesActionPerformed

    private void jButtonDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosPersonalesActionPerformed
        PanelModificarDatosPersonales panel = new PanelModificarDatosPersonales(this.socio);
        this.setVisible(false);
        panel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonDatosPersonalesActionPerformed

    private void jButtonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservasActionPerformed
        PanelUsuReservas panel2 = new PanelUsuReservas(this.socio);
        this.setVisible(false);
        panel2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
    // 1. Creamos un socio falso solo para esta prueba de diseño
    ArrayList<String> prueba = new ArrayList<>();
    prueba.add("5555666677778888");
    prueba.add("04/27");
    Socio socioDummy = new Socio("Socio Prueba", "socio@prueba.com", "1234", "DireccionPrueba", "959699444", prueba, false);
    
    // 2. Se lo pasamos a la ventana para que nos permita construirla
    new PanelUsuario(socioDummy).setVisible(true);
    });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActividades;
    private javax.swing.JButton jButtonDatosPersonales;
    private javax.swing.JButton jButtonReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNomUsuario;
    // End of variables declaration//GEN-END:variables
}
