/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl2.darioedu;

import java.util.List;

/**
 *
 * @author User
 */
public class PanelConsultaSocios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelConsultaSocios.class.getName());
    private final Administrador usuario;
    private JPanelBusqueda barraBusqueda;
    private JPanelLista listaPanel;
    /**
     * Creates new form PanelConsultaSocios
     */
    public PanelConsultaSocios(Administrador admin) {
        initComponents();
        this.usuario = admin;
        iniciarNuevo();
        this.barraBusqueda = new JPanelBusqueda();
        this.barraBusqueda.setBusquedaAdminSocio();
        this.jPanel1.add(this.barraBusqueda);
    }
    
    public final void iniciarNuevo(){
        this.listaPanel = new JPanelLista();
        this.listaPanel.modoAdminListaUsuarios();
        this.jScrollPane1.setViewportView(this.listaPanel);
        this.jScrollPane1.revalidate();
        this.jScrollPane1.repaint();
        
   }
    public void busqueda(){
        this.barraBusqueda.setBusqueda();
        if (this.barraBusqueda.busquedaValida()){
            //Parte cuando la búsqueda es Exitosa,
            List<Usuario> listaUs = this.barraBusqueda.getBusquedaAdminSocio();
            this.barraBusqueda.setTextArea("");
            this.listaPanel = new JPanelLista();
            this.listaPanel.modoAdminListaUsuariosFiltrado(listaUs);
            this.jScrollPane1.setViewportView(this.listaPanel);
            this.jScrollPane1.revalidate();
            this.jScrollPane1.repaint();
                this.barraBusqueda.setTextArea("");
            
        }else{
                this.barraBusqueda.setTextArea("");
                iniciarNuevo();
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolverAtras = new javax.swing.JButton();
        ButtonAddUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ButonBusqueda = new javax.swing.JButton();
        BotonAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit - Admin Menu User Search - Version "+Globales.version);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jButtonVolverAtras.setBackground(new java.awt.Color(255, 153, 51));
        jButtonVolverAtras.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonVolverAtras.setText("<-");
        jButtonVolverAtras.addActionListener(this::jButtonVolverAtrasActionPerformed);

        ButtonAddUsuario.setBackground(new java.awt.Color(255, 153, 51));
        ButtonAddUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ButtonAddUsuario.setText("Añadir Socio");
        ButtonAddUsuario.addActionListener(this::ButtonAddUsuarioActionPerformed);

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 70));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        ButonBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar.png"))); // NOI18N
        ButonBusqueda.setMaximumSize(new java.awt.Dimension(50, 50));
        ButonBusqueda.setMinimumSize(new java.awt.Dimension(50, 50));
        ButonBusqueda.setPreferredSize(new java.awt.Dimension(50, 50));
        ButonBusqueda.addActionListener(this::ButonBusquedaActionPerformed);
        jPanel1.add(ButonBusqueda);

        BotonAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AyudaBoton.png"))); // NOI18N
        BotonAyuda.setMaximumSize(new java.awt.Dimension(50, 50));
        BotonAyuda.setMinimumSize(new java.awt.Dimension(50, 50));
        BotonAyuda.setPreferredSize(new java.awt.Dimension(50, 50));
        BotonAyuda.addActionListener(this::BotonAyudaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(BotonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed
        // Codigo para volver al panel de admin
        this.setVisible(false);
        new PanelAdmin(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void ButtonAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddUsuarioActionPerformed

    }//GEN-LAST:event_ButtonAddUsuarioActionPerformed

    private void ButonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonBusquedaActionPerformed
        this.busqueda();
    }//GEN-LAST:event_ButonBusquedaActionPerformed

    private void BotonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAyudaActionPerformed
        new PanelAyuda("Este panel sirve para que puedas ver los socios inscritos en el gimnasio. Permite visualizar su información más relevante y se puede editar parte de su info").setVisible(true);
    }//GEN-LAST:event_BotonAyudaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.iniciarNuevo();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAyuda;
    private javax.swing.JButton ButonBusqueda;
    private javax.swing.JButton ButtonAddUsuario;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
