package pl2.darioedu;

import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Darío :)
 */
public class VentanaPrueba extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrueba.class.getName());

    /**
     * 
     */
    public VentanaPrueba() {
        initComponents();
        JPanelBusqueda barraBusqueda = new JPanelBusqueda();
        barraBusqueda.setBusquedaAdminSocio();
        this.jPanel1.add(barraBusqueda);
        JPanelLista listaPanel = new JPanelLista();
        listaPanel.modoAdminListaUsuarios();
        if (barraBusqueda.busquedaValida()){
            List<Usuario> listaUs = barraBusqueda.getBusquedaAdminSocio();
            listaPanel.modoAdminListaUsuariosFiltrado(listaUs);
        }
        else{
            JLabel mensaje = new JLabel();
            listaPanel.add(mensaje);
        }
        this.jScrollPane1.add(listaPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Prueba - Panel Mostrar Info Usuarios");
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 70));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(320, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(320, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(320, 300));
        jScrollPane1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VentanaPrueba aux = new VentanaPrueba();
        aux.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
