package pl2.darioedu;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author Darío :)
 */
public class VentanaPrueba1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrueba1.class.getName());
    private JPanelBusqueda barraBusqueda;
    private JPanelLista listaPanel;
    private Socio socio;
    /**
     * 
     */
   public final void iniciarNuevo(){
        this.barraBusqueda = new JPanelBusqueda();
        this.barraBusqueda.setBusquedaUsuarioActividad();
        this.jPanel1.add(this.barraBusqueda);
        this.listaPanel = new JPanelLista();
        this.listaPanel.modoUsuarioListaBusqueda(Main.getListaActividadStatic());
        this.jScrollPane1.setViewportView(this.listaPanel);
   }
    
       public void ventanaEmergenteSeleccionado(){
        JFrame ventana = new JFrame("Calendario");
        JPanelCalendario aux = new JPanelCalendario();
        ventana.add(aux);
        ventana.setSize(250,480);
        ventana.setVisible(true);
        
    }
    
    public VentanaPrueba1() {
        initComponents();
        iniciarNuevo();
    }
    public void busqueda(){
        if (this.barraBusqueda.busquedaValida()){
            this.barraBusqueda.setTextArea(null);
            List<Actividad> listaAct = this.barraBusqueda.getBusquedaUsuarioActividad();
            this.listaPanel = new JPanelLista();
            this.listaPanel.modoUsuarioListaBusqueda(listaAct);
            this.jScrollPane1.setViewportView(this.listaPanel);
            this.jScrollPane1.revalidate();
            this.jScrollPane1.repaint();
        }
        
    }
    public void resetearPulsado(){
        this.listaPanel.ResetearInformacionObtenida();
        this.listaPanel.ResetearListaInformacionBotones();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Prueba - Panel Mostrar Info Usuarios");
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 70));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar.png"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(320, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(320, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(320, 300));
        jScrollPane1.setRequestFocusEnabled(false);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.busqueda();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
    if (this.barraBusqueda.getSeleccionado().equals("Dia")){
          this.ventanaEmergenteSeleccionado();
        }
    }//GEN-LAST:event_jScrollPane1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
